version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_fisioapp
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: usuario
      POSTGRES_DB: fisioapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local